import type { ClerkAppearanceTheme } from "@clerk/shared/types";

export const clerkAppearance: ClerkAppearanceTheme = {
  variables: {
    colorPrimary: "#7c3aed",
    colorPrimaryForeground: "#ffffff",
    colorBackground: "#12121a",
    colorForeground: "#ffffff",
    colorInput: "rgba(255, 255, 255, 0.05)",
    colorInputForeground: "#ffffff",
    colorMuted: "rgba(255, 255, 255, 0.05)",
    colorMutedForeground: "#a1a1aa",
    colorBorder: "rgba(255, 255, 255, 0.1)",
    colorNeutral: "#ffffff",
    colorDanger: "#ef4444",
    colorSuccess: "#34d399",
    colorWarning: "#f97316",
    colorShadow: "#000000",
    colorRing: "#7c3aed",
    colorModalBackdrop: "rgba(11, 11, 18, 0.8)",
    fontFamily: "inherit",
    borderRadius: "0.75rem",
  },
  elements: {
    card: "bg-[#12121a] border border-white/10 shadow-2xl",
    modalContent: "bg-[#12121a]",
    modalBackdrop: "bg-[#0b0b12]/80 backdrop-blur-sm",
    headerTitle: "text-white",
    headerSubtitle: "text-zinc-400",
    socialButtonsBlockButton: "border border-white/10 bg-white/5 hover:bg-white/10 text-white",
    socialButtonsBlockButtonText: "text-white",
    dividerRow: "text-zinc-500",
    dividerLine: "bg-white/10",
    dividerText: "text-zinc-500",
    formFieldLabel: "text-zinc-300",
    formFieldInput: "bg-white/5 border border-white/10 text-white focus:border-violet-500/50",
    formButtonPrimary: "bg-violet-600 hover:bg-violet-500 text-white shadow-none",
    footerActionText: "text-zinc-400",
    footerActionLink: "text-violet-400 hover:text-violet-300",
    identityPreviewText: "text-zinc-300",
    identityPreviewEditButton: "text-violet-400",
    avatarBox: "h-8 w-8",
    userButtonAvatarBox: "h-8 w-8",
    userButtonPopoverCard: "bg-[#12121a] border border-white/10 shadow-2xl",
    userButtonPopoverActionButton: "text-zinc-300 hover:bg-white/5",
    userButtonPopoverActionButtonIcon: "text-zinc-400",
  },
};
